version: "3.7"

services:
  gateway:
    container_name: gateway
    ports:
      - 80:80
    build:
      context: gateway
    depends_on:
      - frontend
      - backend
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
  frontend:
    container_name: frontend
    ports:
      - 8080:8080
    build:
      context: frontend
      target: development
    volumes:
      - ./frontend:/home/node
      - /home/node/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    container_name: backend
    build:
      context: backend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV
    volumes:
      - ./backend/test.env:/home/node/undefined.env
  db:
    image: "postgres:12"
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: adde
    ports:
      - 5432:5432
