name: Build
on: [push, pull_request]

jobs:
  build_and_push:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      # ---------- Frontend Build ------------- #
      - uses: docker/setup-buildx-action@v1
      - name: Build the Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          load: true
          tags: |
            ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
      - name: Yarn Test
        run: docker run -v `pwd`/frontend/coverage:/home/node/coverage ghcr.io/${{ github.repository }}/frontend:${{ github.sha }} yarn test
      # ---------- Backend Build ------------- #
      - name: Download Test secrets
        run: echo '${{ secrets.TESTENVIRONMENT }}' > backend/test.env
      - name: Download Test key
        run: echo '${{ secrets.PRIVATEKEY}}' > backend/private-key.pem
      - name: Build the Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          load: true
          tags: |
            ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
      - name: Prepare
        run: |
          mkdir -p backend/cache/devopslibrary/sampledata && git clone https://github.com/devopslibrary/sampledata.git backend/cache/devopslibrary/sampledata
          touch backend/test-report.xml && mkdir backend/coverage
          docker create -v `pwd`/backend/coverage:/home/node/coverage -v `pwd`/backend/test-report.xml:/home/node/test-report.xml --user $UID:$GID --name backend ghcr.io/${{ github.repository }}/backend:${{ github.sha }} yarn test
          docker cp `pwd`/backend/private-key.pem backend:/home/node/private-key.pem
          docker cp `pwd`/backend/test.env backend:/home/node/production.env
          docker cp `pwd`/backend/cache backend:/tmp/cache
          docker start -a backend
      # ---------- Push Containers ------------- #
      - name: Push the tagged Docker Images
        run: |
          docker push ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/frontend:latest
          docker push ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/backend:latest
